Bit 76
bitrepository/reference pull request #35
Opened 2022-08-03 07:13 UTC by m-atlantis

2022-08-03 11:45 UTC, ole-v-v approved these changes

2022-08-03 11:45 UTC, ole-v-v commented on bitrepository-integrity-service/src/main/java/org/bitrepository/integrityservice/web/RestIntegrityService.java
> +        }};
Asking without knowing, does the method need to return a `HashMap`, or would any other `Map` do? In the former case, could we please use `return new HashMap<>(Map.of(pillarID, fileList));`? I suggest that we don't like double brace initializations.

2022-08-03 11:45 UTC, ole-v-v commented on bitrepository-integrity-service/src/main/java/org/bitrepository/integrityservice/web/RestIntegrityService.java
> +    public HashMap<String, List<String>> getMissingFileIDs(
The methods `getMissingFileIDs` and `getAllMissingFilesInformation` are the same. Do we need both? If so, could they share their implementation? (Intellij IDEA drew my attention to this one.) There could be opportunities fr even more code reuse in the file.

2022-08-03 11:45 UTC, ole-v-v commented on bitrepository-webclient/src/main/webapp/integrity-service.html
> +  <!-- Not used with new modal. -->
Would deleting the lines completely harm?

2022-08-04 09:51 UTC, m-atlantis commented
Fixed the issues and have re-requested a review

2022-08-04 10:10 UTC, ole-v-v approved these changes
Thanks, like.

2022-08-15 12:56 UTC, Bohlski requested changes
Looks good (except the stuff that didn't work :P), but I'm not sure I agree with removing paging from the REST endpoints completely. 

Perhaps it could be fine for checksum errors etc. to just all be grabbed in one go, but calling the getAllFileIDs endpoint on a bitrepository in production could possibly result in many millions of file IDs being returned, which I'm not convinced wouldn't be very slow. As I see it, there was a reason why paging was being done in the first place - but I definitely also think that there should be an option to get all IDs.

2022-08-17 09:31 UTC, ole-v-v approved these changes

2022-08-18 13:39 UTC, Bohlski requested changes

2022-08-18 13:39 UTC, Bohlski commented on bitrepository-integrity-service/src/main/java/org/bitrepository/integrityservice/web/StreamingTools.java
> +    public static List<String> IteratorToList(IntegrityIssueIterator iterator) {
camelCase? :)

2022-08-18 13:39 UTC, Bohlski commented on bitrepository-integrity-service/src/main/java/org/bitrepository/integrityservice/web/StreamingTools.java
> +    public static List<String> FilePartToList(File source, int offset, int maxLines) {
camelCase? :)

2022-08-18 13:39 UTC, Bohlski commented on bitrepository-webclient/src/main/webapp/integrity-service.html
> +        // }
Do TODO

2022-08-25 13:48 UTC, Bohlski requested changes
Looking good. There was a small change I imagine was accidentally committed that made modals not work, but I fixed it in the merge that I'll push following this.

2022-08-25 13:48 UTC, Bohlski commented on bitrepository-webclient/src/main/webapp/integrity-service.html
> +            $("#" + innerElement).click(showModal(type, context.title, context.url, pillarID));
I fixed this on my local branch that I'll push, but `context.member` got removed here, which left things not working.

2022-08-25 13:48 UTC, Bohlski commented on bitrepository-webclient/src/main/webapp/integrity-service.html
>      }
Can't `getMaxPages` just return `pillars[pillarID][member]` directly instead of returning it as a function that is called later on?

2022-08-25 13:48 UTC, Bohlski commented on bitrepository-webclient/src/main/webapp/table-modal.js
> +            for (let k = 0; k < pillars.length; k++) {
I'd probably rename `k` to `j` for conventions sake as variable name `j` is no longer occupied with the change to the better name `json`. :)

2022-08-29 08:35 UTC, Bohlski commented on bitrepository-webclient/src/main/webapp/integrity-service.html
>      }
This has been updated with both a more meaningful name and a comment explaining why an anonymous function is returned.

2022-08-29 08:43 UTC, Bohlski approved these changes

2022-08-29 08:46 UTC, merged